### ISSUE TITLE
Cannot pip install anything after loading nix/nse/bluepy

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/bbp-nixpkgs#901]
Hi,

it seems that it is not currently possible to pip install any package after module loading `bluepy` in bb5. This is not the case if I load other modules.

``` 
module load nix/python/2.7-full
virtualenv blah
source blah/bin/activate
# after this I can still pip install packages
module load nix/nse/bluepy
# every pip install ends up with a KeyError
```

``` python
Exception:
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_internal/operations/check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2613, in requires
    dm = self._dep_map
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2864, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2855, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/gpfs/bbp.cscs.ch/home/zisis/blah/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1794, in get_metadata
    raise KeyError("No metadata except PKG-INFO is available")
KeyError: 'No metadata except PKG-INFO is available'
```

**Comment by eleftherioszisis** [comment]
@tristan0x @adevress Any insights concerning this issue? I need to work with Bluepy and this is currently blocking me.

**Comment by tristan0x** [comment]
Hello @eleftherioszisis 
I have never encountered this issue. I will investigate on this matter this week. In the mean time, can you `pip install` the packages you need before loading bluepy module?

**Comment by eleftherioszisis** [comment]
Yes, without bluepy I can install all the packages I need and everything works as expected.

Regardless of their type, the rest of the modules I am using (python, c libraries) exhibit no issues. It all breaks down after `bluepy` is included in the modules.

Thank you for looking into this!

**Comment by tristan0x** [comment]
Hello @eleftherioszisis 
I can reproduce the issue.
nix/nse/bluepy seems to provide packages that conflict with virtualenv. For instance nix/nse/bluepy should not provide `pkgconfig`.
I will shake the bluepy Nix recipe a little bit to see if I can fix it.

**Comment by tristan0x** [comment]
Actually the problem comes a broken symbolic link in numpy-quaternion Python package, a bluepy dependency.

after load nix/nse/bluepy module, PYTHONPATH provide this symbolic link pointing to an unexisting file:
`/nix/store/dcl1rbpjna1jhhkhzsy87vhhcknmzd26-generated-env-module-bluepy/lib/python2.7/site-packages/numpy_quaternion-2018.6.22.12.6.52.dist-info`
But the package provides numpy_quaternion-2018.6.22.12.6.54.dist-info.

I will fix that tomorrow.

**Comment by tristan0x** [comment]
This works now

**Comment by tristan0x** [comment]
@eleftherioszisis Can you please confirm that it works on your side?

**Comment by eleftherioszisis** [comment]
Yes indeed it works. Many thanks for the fix!
